In [16]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [17]:
# import dataset
data = pd.read_csv('patient_dataset.csv')
X = data.iloc[:, :-1].values
Y = data.iloc[:, -1].values

# menampilkan data
data.head()

age  gender  chest_pain_type  blood_pressure  cholesterol  max_heart_rate  \
0   24     1.0                4             250          139             212   
1   29     0.0                4             132          187             147   
2   46     0.0                3             271          185             193   
3   73     NaN                2             102          200             125   
4   49     1.0                3              91          163             192   

   exercise_angina  plasma_glucose  skin_thickness  insulin        bmi  \
0                0           108.0            33.0    109.0  37.999303   
1                0           202.0            42.0      NaN  25.588346   
2                0           149.0            43.0    102.0  37.892029   
3                0           105.0            77.0    165.0  18.660241   
4                0           162.0            31.0    170.0  12.767980   

   diabetes_pedigree  hypertension  heart_disease residence_type  \
0           0.480277             1              1          Urban   
1           0.283986             1              1          Urban   
2           2.472309             1              0          Rural   
3           1.472052             0              1          Rural   
4           0.537627             1              1          Rural   

  smoking_status  
0         Smoker  
1        Unknown  
2     Non-Smoker  
3         Smoker  
4         Smoker

In [18]:
print(X)
print(Y)

[[24 1.0 4 ... 1 1 'Urban']
 [29 0.0 4 ... 1 1 'Urban']
 [46 0.0 3 ... 1 0 'Rural']
 ...
 [70 0.0 2 ... 0 1 'Urban']
 [78 0.0 2 ... 1 0 'Urban']
 [28 1.0 4 ... 1 0 nan]]
['Smoker' 'Unknown' 'Non-Smoker' ... 'Non-Smoker' 'Non-Smoker'
 'Non-Smoker']


In [19]:
# menghilangkan missing value
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [20]:
# encoding data kategori
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [13,14])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[0.0 1.0 0.0 ... 37.99930321170566 0.4802774784768699 1]
 [0.0 1.0 0.0 ... 25.5883457763562 0.2839863775233223 1]
 [1.0 0.0 1.0 ... 37.892029036429335 2.4723085919346364 1]
 ...
 [0.0 1.0 0.0 ... 40.48395635352023 0.6460219716531521 0]
 [1.0 0.0 0.0 ... 24.98707108315713 0.719095457948519 1]
 [1.0 0.0 0.0 ... 11.348716298084636 1.53848861093208 1]]


In [21]:
# encoding data kategori
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)
print(Y)

[1 2 0 ... 0 0 0]


In [22]:
# membagi data training dan testing
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=1)


In [23]:
print(X_train)

[[1.0 0.0 0.0 ... 41.72341620734944 0.2869346045592387 0]
 [0.0 1.0 0.0 ... 38.83487779167436 2.1322570406009462 1]
 [1.0 0.0 1.0 ... 30.6705688290341 0.4315113402908843 0]
 ...
 [0.0 1.0 0.0 ... 39.28075271590959 1.6818931986539174 0]
 [1.0 0.0 0.0 ... 29.385682652764057 1.9335537107603653 0]
 [1.0 0.0 0.0 ... 17.892733000321385 1.736595530504464 1]]


In [24]:
print(X_test)

[[0.0 1.0 0.0 ... 35.06718123392973 1.152181497640379 1]
 [1.0 0.0 0.0 ... 20.733260257033635 0.3313495450788283 0]
 [1.0 0.0 0.0 ... 32.122968422531784 2.260123383161317 1]
 ...
 [0.0 1.0 1.0 ... 12.890671523571262 1.1228504604067144 0]
 [1.0 0.0 0.0 ... 38.44860033403033 1.6970216523560455 0]
 [0.0 1.0 0.0 ... 48.65599775706332 1.1602176164871374 1]]


In [25]:
print(Y_train)

[1 1 0 ... 0 0 1]


In [26]:
print(Y_test)

[1 0 1 ... 0 1 1]


In [27]:
# feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 15:] = sc.fit_transform(X_train[:, 15:])
X_test[:, 15:] = sc.transform(X_test[:, 15:])

In [28]:
print(X_train)

[[1.0 0.0 0.0 ... 1.0154662327205857 -1.4571523464869758
  -1.0008336808451122]
 [0.0 1.0 0.0 ... 0.7666264689773674 1.2227694178843196
  0.9991670135997417]
 [1.0 0.0 1.0 ... 0.06329335685213532 -1.247186687834876
  -1.0008336808451122]
 ...
 [0.0 1.0 0.0 ... 0.8050373864862456 0.5687157748209142
  -1.0008336808451122]
 [1.0 0.0 0.0 ... -0.04739610838221925 0.9341968801574844
  -1.0008336808451122]
 [1.0 0.0 0.0 ... -1.037482603582301 0.6481587853348922
  0.9991670135997417]]


In [29]:
print(X_test)

[[0.0 1.0 0.0 ... 0.44204961163057166 -0.2005730435784285
  0.9991670135997417]
 [1.0 0.0 0.0 ... -0.7927788711926961 -1.3926494913561263
  -1.0008336808451122]
 [1.0 0.0 0.0 ... 0.18841364943520758 1.408466934841377
  0.9991670135997417]
 ...
 [0.0 1.0 1.0 ... -1.4683966566372793 -0.243169873009871
  -1.0008336808451122]
 [1.0 0.0 0.0 ... 0.7333497118541611 0.5906865001238499
  -1.0008336808451122]
 [0.0 1.0 0.0 ... 1.6126893631452583 -0.18890236241297426
  0.9991670135997417]]
